import type { Theme } from 'theme-ui'

export const theme: Theme = {
  fonts: {
    maison: 'Maison',
  },
  fontWeights: {
    light: 300,
    regular: 400,
    medium: 500,
    demi: 600,
    semiBold: 700,
    extraBold: 900,
    large: 950,
  },
  colors: {
    // Colors from HEAD branch
    primary_text_dark: '#303030',
    grey_medium: '#85878a',
    orange_500: '#ff7b00',
    teal_disabled: '#00C6B7',
    grey_disabled_text: '#ADAF8B',
    orange_accent_alpha: '#fc790dd9',
    orange_light_bg: '#ffbe9d',
    dark_black: '#1e293b',
    orange_light_200: '#fc790d66',
    grey_dark: '#666666',
    grey_border: '#ccc',
    grey_subtext: '#898989',
    blue_primary: '#2E37A4',
    blue_translucent: 'rgba(46, 55, 164, 0.5)',
    yellow_status_bg: '#FFE5A0',
    blue_bg_secondary: '#DEF0F6',
    text_primary_strong: '#2b2b2b',
    green_deep: '#023E1A',
    grey_light: '#c0c2c6',
    orange_alert: '#E15517',
    blue_dark: '#122e5d',
    black_soft: '#4a4a4a',
    primary_grenade: '#EF9700',
    charcoal_gray: '#212529',
    primary_cream: '#F9F4ED',
    primary_spinach: '#043F12',
    grey_200: '#848794',
    grey_300: '#eeeeee',
    red_500: '#FF0000',
    red_600: '#CC0000',
    red_50: '#FFE5E5',
    gret_800: '#85888e',
    grey_500: '#4a5568',
    blue_primary_button: '#0047AB',
    blue_primary_button_gradient: 'linear-gradient(135deg, #ff6b35, #f7931e)',
  },
  text: {
    Maison16Medium20: {
      fontFamily: 'maison',
      fontWeight: 'medium',
      lineHeight: '125%',
      fontSize: [14, 14, 16, 16, 16],
    },
    Maison16Demi20: {
      fontFamily: 'maison',
      fontWeight: 'demi',
      lineHeight: '125%',
      fontSize: [14, 14, 16, 16, 16],
    },
    Maison28Demi20: {
      fontFamily: 'maison',
      fontWeight: 'demi',
      lineHeight: '125%',
      fontSize: [20, 22, 24, 26, 28],
    },
    Maison16Regular20: {
      fontFamily: 'maison',
      fontWeight: 'regular',
      lineHeight: '125%',
      color: 'primary_text_dark',
      fontSize: [14, 14, 16, 16, 16],
    },
    Maison14Regular20: {
      fontFamily: 'maison',
      fontWeight: 'regular',
      lineHeight: '125%',
      color: 'primary_text_dark',
      fontSize: 14,
    },
    Maison12Regular20: {
      fontFamily: 'maison',
      fontWeight: 'regular',
      lineHeight: '125%',
      fontSize: 12,
    },
    Maison18Demi111: {
      fontFamily: 'maison',
      color: 'primary_text_dark',
      fontWeight: 'demi',
      lineHeight: '111.111%',
      fontSize: [16, 16, 17, 18, 18],
    },
    Maison18Medium125: {
      fontFamily: 'maison',
      fontWeight: 'medium',
      color: 'primary_text_dark',
      lineHeight: '125%',
      fontSize: [14, 14, 16, 18, 18],
    },
    Maison60Demi125: {
      color: 'primary_text_dark',
      fontFamily: 'maison',
      fontWeight: 'demi',
      lineHeight: '125%',
      fontSize: [30, 30, 40, 50, 60],
    },
    Maison20SemiBold125: {
      fontFamily: 'maison',
      fontWeight: 'semiBold',
      color: 'primary_text_dark',
      lineHeight: '125%',
      fontSize: [14, 14, 16, 18, 20],
    },
    Maison36SemiBold125: {
      color: 'primary_text_dark',
      fontFamily: 'maison',
      fontWeight: 'semiBold',
      lineHeight: '125%',
      fontSize: [20, 22, 30, 34, 36],
    },
    Maison36Medium125: {
      color: 'primary_text_dark',
      fontFamily: 'maison',
      fontWeight: 'medium',
      lineHeight: '125%',
      fontSize: [20, 22, 30, 34, 36],
    },
    Maison24Medium125: {
      color: 'primary_text_dark',
      fontFamily: 'maison',
      fontWeight: 'medium',
      lineHeight: '125%',
      fontSize: [18, 20, 24, 24, 24],
    },
    Maison24MDemi125: {
      color: 'primary_text_dark',
      fontFamily: 'maison',
      fontWeight: 'demi',
      lineHeight: '125%',
      fontSize: [18, 20, 24, 24, 24],
    },
    Maison20Medium125: {
      color: 'orange_accent_alpha',
      fontFamily: 'maison',
      fontWeight: 'medium',
      lineHeight: '125%',
      fontSize: [16, 18, 18, 20, 20],
    },
    Maison20Demi125: {
      color: 'orange_accent_alpha',
      fontFamily: 'maison',
      fontWeight: 'demi',
      lineHeight: '125%',
      fontSize: [16, 18, 18, 20, 20],
    },
    Maison18Demi125: {
      color: 'primary_text_dark',
      fontFamily: 'maison',
      fontWeight: 'demi',
      lineHeight: '125%',
      fontSize: [14, 14, 16, 18, 18],
    },
    Maison14Medium20: {
      fontFamily: 'maison',
      fontWeight: 'medium',
      lineHeight: '125%',
      fontSize: 14,
    },
    Maison28Medium20: {
      color: 'primary_text_dark',
      fontFamily: 'maison',
      fontWeight: 'medium',
      lineHeight: '125%',
      fontSize: [22, 23, 24, 27, 28],
    },
    Maison18Regular20: {
      color: 'black2',
      fontFamily: 'maison',
      fontWeight: 'regular',
      lineHeight: '125%',
      fontSize: [14, 14, 16, 18, 18],
    },
    Maison22Regular125: {
      color: 'primary_text_dark',
      fontFamily: 'maison',
      fontWeight: 'regular',
      lineHeight: '125%',
      fontSize: [16, 21, 22, 22, 23],
    },
    Maison22Medium125: {
      color: 'primary_text_dark',
      fontFamily: 'maison',
      fontWeight: 'medium',
      lineHeight: '125%',
      fontSize: [16, 21, 22, 22, 22],
    },
    Maison22Demi125: {
      color: 'primary_text_dark',
      fontFamily: 'maison',
      fontWeight: 'demi',
      lineHeight: '125%',
      fontSize: [16, 21, 22, 26, 26],
    },
    Maison14Medium18: {
      fontSize: 14,
      lineHeight: 18,
      fontWeight: 500,
    },
  },
  buttons: {
    primary: {
      background: 'blue_primary_button_gradient',
      padding: '12px 32px',
      borderRadius: '62px',
      color: 'primary_cream',
      position: 'relative',
      overflow: 'hidden',
      transition: 'all 0.2s ease-in-out',
      transform: 'translateY(0)',
      ':hover': {
        transform: 'translateY(-1px)',
        filter: 'brightness(1.05)',
        boxShadow:
          '0 4px 12px rgba(239, 151, 0, 0.3), 0 2px 6px rgba(239, 151, 0, 0.2)',
      },
      '::before': {
        content: '""',
        position: 'absolute',
        top: 0,
        left: '-100%',
        width: '100%',
        height: '100%',
        background:
          'linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.2), transparent)',
        transition: 'left 0.5s ease-in-out',
        pointerEvents: 'none',
        zIndex: 1,
      },
      ':hover::before': {
        left: '100%',
      },
      ':active': {
        transform: 'translateY(0)',
        transition: 'transform 0.1s ease-in-out',
      },
      ':disabled': {
        backgroundColor: 'orange_light_200',
        color: 'txtDisable !important',
        cursor: 'not-allowed',
        transform: 'none',
        filter: 'none',
        boxShadow: 'none',
        '::before': {
          display: 'none',
        },
        opacity: 0.5,
      },
    },
    darkSlate: {
      background: '#1e293b',
      padding: '12px 32px',
      borderRadius: '8px',
      color: 'white',
      fontWeight: 'semiBold',
      fontSize: [14, 14, 16, 16, 16],
      position: 'relative',
      overflow: 'hidden',
      transition: 'all 0.2s ease-in-out',
      transform: 'translateY(0)',
      ':focus': {
        border: '1px solid #00C6B7',
      },
      '&:hover': {
        backgroundColor: '#334155',
        borderColor: '#334155',
        transform: 'translateY(-1px)',
        boxShadow:
          '0 4px 12px rgba(30, 41, 59, 0.2), 0 2px 6px rgba(30, 41, 59, 0.15)',
      },
      // ':hover': {
      //   background: '#334155',
      //   transform: 'translateY(-1px)',
      //   boxShadow:
      //     '0 4px 12px rgba(30, 41, 59, 0.3), 0 2px 6px rgba(30, 41, 59, 0.2)',
      // },
      '&::before': {
        content: '""',
        position: 'absolute',
        top: 0,
        left: '-100%',
        width: '100%',
        height: '100%',
        background:
          'linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.2), transparent)',
        transition: 'left 0.5s',
        pointerEvents: 'none',
        zIndex: 1,
      },
      '&:hover::before': {
        left: '100%',
      },
      ':disabled': {
        backgroundColor: '#64748b',
        color: '#94a3b8',
        cursor: 'not-allowed',
        transform: 'none',
        boxShadow: 'none',
      },
    },
    FeatureChipBtn: {
      background: '#d5d5d5',
      padding: '4px',
      borderRadius: '2px',
      color: 'primary_text_dark',
      width: '100%',
    },
    primaryBorderBtn: {
      backgroundColor: 'transparent',
      padding: '8px 16px',
      borderRadius: '60px',
      color: 'white',
      border: '1px solid #848794',
      ':focus': {
        border: '1px solid #00C6B7',
      },
      ':active': {
        backgroundColor: 'teal_disabled',
      },
      ':disabled': {
        backgroundColor: 'orange_light_200',
        color: 'txtDisable !important',
        cursor: 'not-allowed',
      },
    },
    secondary: {
      background: 'primary_spinach',
      padding: '8px 16px',
      borderRadius: '8px',
      color: 'white',
      ':focus': {
        border: '1px solid #00C6B7',
      },
      ':active': {
        backgroundColor: 'teal_disabled',
      },
      ':disabled': {
        backgroundColor: 'orange_light_200',
        color: 'txtDisable !important',
        cursor: 'not-allowed',
      },
    },
    primaryBlue: {
      background: 'blue_primary_button',
      padding: '8px 16px',
      borderRadius: '4px',
      color: 'white',
      ':focus': {
        border: '1px solid #00C6B7',
      },
      ':active': {
        backgroundColor: 'teal_disabled',
      },
      ':disabled': {
        backgroundColor: 'orange_light_200',
        color: 'txtDisable !important',
        cursor: 'not-allowed',
      },
    },
    resendOTPBtn: {
      backgroundColor: 'transparent',
      padding: 'unset',
      color: 'grey_medium',
      fontFamily: 'maison',
      fontWeight: 'regular',
      lineHeight: '125%',
      fontSize: 16,
      textDecoration: 'underline',
      ':disabled': {
        color: 'grey_border',
        cursor: 'not-allowed',
        textDecoration: 'unset',
      },
    },
    Border50PrimaryGrenade: {
      background: 'orange_accent_alpha',
      color: 'white',
      fontWeight: 'medium',
      fontFamily: 'maison',
      fontSize: [14, 14, 16, 16, 18, 18],
      borderRadius: '100px',
      ':hover': {
        boxShadow: '0px 0px 10px 0px rgba(41, 113, 137, 0.20)',
      },
      ':disabled': {
        backgroundColor: 'orange_light_200',
      },
      padding: '14px 20px',
    },
    secondary2: {
      background: 'blue_bg_secondary',
      color: 'primary_text_dark',
      minWidth: '104px',
      fontSize: [16, 16, 16, 16, 16, 18, 18],
      ':hover': {
        boxShadow: '0px 0px 10px 0px rgba(41, 113, 137, 0.20)',
      },
      ':focus': {
        border: '1px solid #00C6B7',
      },
      ':active': {
        backgroundColor: 'disableDarkBlue',
        color: 'white',
      },
    },
    secondary3: {
      background: 'orange_500',
      color: 'white',
      width: '100%',
      minWidth: ['80px', '100px', '130px', '140px'],
      fontWeight: 'medium',
      fontFamily: 'maison',
      fontSize: [14, 14, 16, 16, 18, 18],
      borderRadius: '6px',
      ':hover': {
        boxShadow: '0px 0px 10px 0px rgba(41, 113, 137, 0.20)',
      },
      ':active': {
        backgroundColor: 'disableDarkBlue',
        color: 'white',
      },
    },
    blue_primary_button: {
      background: 'blue_primary_button',
      color: 'white',
      padding: '8px 16px',
      borderRadius: '8px',
      fontSize: 14,
    },
  },
  forms: {
    primaryInput: {
      borderRadius: '16px',
      border: '2px solid rgba(226, 232, 240, 0.8)',
      padding: '14px 20px',
      color: '#2e4244',
      fontFamily: 'maison',
      fontSize: 16,
      lineHeight: '125%',
      fontWeight: 'medium',
      boxShadow: '0 4px 12px rgba(0, 0, 0, 0.05), 0 1px 3px rgba(0, 0, 0, 0.1)',
      backgroundColor: 'rgba(255, 255, 255, 0.95)',
      width: '100%',
      outline: 'none',
      transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
      ':hover': {
        borderColor: 'rgba(255, 123, 0, 0.4)',
        backgroundColor: 'rgba(255, 255, 255, 1)',
        boxShadow:
          '0 6px 20px rgba(255, 123, 0, 0.1), 0 2px 8px rgba(0, 0, 0, 0.08)',
        transform: 'translateY(-1px)',
      },
      ':focus': {
        borderColor: '#ff7b00',
        boxShadow:
          '0 0 0 4px rgba(255, 123, 0, 0.12), 0 8px 24px rgba(255, 123, 0, 0.15)',
        backgroundColor: 'rgba(255, 255, 255, 1)',
        transform: 'translateY(-1px)',
      },
      ':disabled': {
        backgroundColor: '#F8F9FA',
        color: '#6B7280',
        borderColor: '#E5E7EB',
        cursor: 'not-allowed',
        transform: 'none',
        boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)',
      },
      '::placeholder': {
        color: '#9CA3AF',
        fontSize: 18,
        fontFamily: 'maison',
        fontWeight: 'medium',
        lineHeight: '125%',
        // opacity: 0.8,
      },
    },
    secondaryInput: {
      outlineColor: '#00C6B7',
      border: '1px solid #e7e7e7',
      padding: '34px',
      pl: '20px',
      boxShadow: '0px 0px 2px 0px rgba(2, 0, 0, 0.20)',
      backgroundColor: 'transparent',
      width: '100%',
      height: '100%',
      color: 'black2',
      fontFamily: 'maison',
      fontWeight: 'semiBold',
      lineHeight: '125%',
      fontSize: 23,
      borderRadius: '14px',
      '::placeholder': {
        position: 'relative',
        width: '100%',
        color: 'grey_medium',
        fontFamily: 'maison',
        fontWeight: 'medium',
        lineHeight: '125%',
        fontSize: 20,
        textWrap: 'wrap',
      },
      ':current': {
        position: 'relative',
        top: '11px',
        width: '100%',
      },
      ':disabled': {
        backgroundColor: 'rgb(211, 211, 211)',
      },
      ':focus': {
        border: '1px solid #00C6B7',
      },
    },
    switchInput: {
      bg: '#EAEAEA',
      borderRadius: '17px',
      width: '60px',
      height: '34px',
      position: 'relative',
      '& > div': {
        position: 'absolute',
        bg: 'white',
        borderRadius: '50%',
        width: '18px',
        height: '18px',
        transform: 'translate(5px,5px)',
        transition: 'transform 0.2s ease',
      },
      'input:checked ~ & > div': {
        transform: 'translate(31px, 5px)',
      },
    },
  },
  styles: {
    bgFlowerPatternCenter: {
      background:
        "radial-gradient(75% 100% at 15% 10%, rgba(247, 245, 247, 0) 77%, #f7f5f2 100%), url('/Images/Pattern.png') center",
    },
  },
  cards: {
    selectStoreCard: {
      bg: 'white',
      borderRadius: '10px',
      boxShadow: '0px 0px 3px 0px rgba(0, 0, 0, 0.20)',
      padding: '20px 18px',
    },
  },

  // breakpoints: ['390px', '768px', '1024px', '1280px', '1366px', '1920px'], TODO CHANGE
}
